# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
  - echo "Installing .NET 3.5"
  - DISM /online /enable-feature /featurename:NetFx3 /all
   
after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"
   
build:
  stage: build
  script:
    - echo "Copying required SQL folders"
    - Copy-Item -Path C:\Service\330149\SQL_2012_Standard\ -Destination $pwd.path -recurse -Force
    - Copy-Item -Path C:\Service\330149\SQL_2012_ServicePack3\ -Destination $pwd.path -recurse -Force
    - echo "SQL files copied"
    - echo "------------------"
    - echo "Running SQL Server Install script via Powershell"
    - echo "------------------"
    - .\_scriptFiles\_SQLExpressInstall.ps1
  tags: [sql-build]
  only: [master]
